# Generated by plane-custom v1.34a (manual, non auto-generated)
#
# PATCH (plane-custom) v1.34a:
#  Crea le 3 tabelle del sistema Meeting:
#    - meetings (model Meeting)
#    - meeting_attendees (model MeetingAttendee)
#    - meeting_issue_links (model MeetingIssueLink)
#
#  Effetto su DB: 3 tabelle nuove, vuote. Nessun impatto sui dati esistenti.
#  La privacy "solo invitati" e' enforced dai view (queryset filter), non
#  da regole DB.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0126_v133e_feature_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ===== Meeting =========================================================
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("reminder_minutes_before", models.IntegerField(default=15)),
                ("recurrence_rule", models.CharField(blank=True, max_length=255, null=True)),
                ("recurrence_until", models.DateTimeField(blank=True, null=True)),
                ("excluded_dates", models.JSONField(blank=True, default=list)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "parent_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_meetings",
                        to="db.meeting",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_meetings",
                        to="db.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_meetings",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "db_table": "meetings",
                "ordering": ("start_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                check=models.Q(("end_at__gte", models.F("start_at"))),
                name="meeting_end_at_after_start_at",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["workspace", "start_at", "end_at"],
                name="meeting_ws_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["created_by", "start_at"], name="meeting_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["project"], name="meeting_project_idx"),
        ),
        # ===== MeetingAttendee =================================================
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("tentative", "Tentative"),
                            ("declined", "Declined"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                ("rsvp_token", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("rsvp_comment", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("invitation_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_inapp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_minutes_before", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="db.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Attendee",
                "verbose_name_plural": "Meeting Attendees",
                "db_table": "meeting_attendees",
            },
        ),
        migrations.AddConstraint(
            model_name="meetingattendee",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(("user__isnull", False), ("external_email__isnull", True))
                    | models.Q(("user__isnull", True), ("external_email__isnull", False))
                ),
                name="meeting_attendee_user_xor_email",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendee",
            index=models.Index(fields=["user", "meeting"], name="meeting_attendee_user_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingattendee",
            index=models.Index(fields=["meeting", "status"], name="meeting_attendee_pending_idx"),
        ),
        # ===== MeetingIssueLink ================================================
        migrations.CreateModel(
            name="MeetingIssueLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_links",
                        to="db.issue",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_links",
                        to="db.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Issue Link",
                "verbose_name_plural": "Meeting Issue Links",
                "db_table": "meeting_issue_links",
            },
        ),
        migrations.AddConstraint(
            model_name="meetingissuelink",
            constraint=models.UniqueConstraint(
                fields=("meeting", "issue"),
                name="meeting_issue_link_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingissuelink",
            index=models.Index(fields=["issue"], name="meeting_link_issue_idx"),
        ),
    ]
