# Generated by plane-custom v1.22a (manual, non auto-generated)
#
# PATCH (plane-custom) v1.22a:
#  Aggiunto Project.is_hidden BooleanField default False, db_index=True.
#  Serve a marcare i progetti "fittizi" workspace-level usati come
#  contenitore per task workspace-only.
#
#  Operazioni:
#    1. AddField is_hidden a Project con default False.
#
#  Effetto su DB esistente:
#    - Tutti i progetti esistenti hanno is_hidden=False (default).
#    - Nessun cambio comportamentale fino a quando il frontend non filtra
#      per is_hidden o l'endpoint workspace-project crea il primo
#      progetto hidden.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_v120a_workspace_level_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_hidden",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
