# Generated by plane-custom v1.20a (manual, non auto-generated)
#
# PATCH (plane-custom) v1.20a:
#   Workspace-level shared states (Opzione 3 - True workspace-shared).
#
#   Operazioni:
#     1. AlterField: state.project diventa NULLABLE (back-compat: i record
#        esistenti restano con project popolato, sono "project-local"; i
#        nuovi workspace-shared states avranno project=NULL).
#     2. RemoveConstraint: rimuove il constraint legacy
#        state_unique_name_project_when_deleted_at_null (era applicato a
#        tutti gli stati indistintamente).
#     3. AlterUniqueTogether: rimuove il vecchio unique_together
#        ("name", "project", "deleted_at") perche' su NULL si comporta in
#        modo non utile (ogni NULL e' distinto).
#     4. AddConstraint x 2: due unique conditional indexes che separano
#        gli scope:
#          - state_unique_name_project_when_active:
#              UNIQUE (name, project) WHERE deleted_at IS NULL
#                                       AND project_id IS NOT NULL
#          - state_unique_name_workspace_shared_when_active:
#              UNIQUE (name, workspace) WHERE deleted_at IS NULL
#                                         AND project_id IS NULL
#
#   Effetto su DB esistente:
#     - Nessun record viene creato/modificato/cancellato.
#     - Solo schema constraint cambia.
#     - Tutti gli issue.state_id continuano a puntare ai loro project state
#       (project_id NOT NULL): nessun aggiornamento dati richiesto.

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        # 1. project FK NULLABLE
        migrations.AlterField(
            model_name="state",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="project_state",
                to="db.project",
            ),
        ),
        # 2. Rimuove vecchio constraint name (introdotto stock per evitare
        #    duplicati su soft-delete).
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_name_project_when_deleted_at_null",
        ),
        # 3. Rimuove unique_together legacy.
        migrations.AlterUniqueTogether(
            name="state",
            unique_together=set(),
        ),
        # 4a. Nuovo unique condizionale per state project-local.
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("name", "project"),
                condition=Q(("deleted_at__isnull", True), ("project__isnull", False)),
                name="state_unique_name_project_when_active",
            ),
        ),
        # 4b. Nuovo unique condizionale per state workspace-shared.
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("name", "workspace"),
                condition=Q(("deleted_at__isnull", True), ("project__isnull", True)),
                name="state_unique_name_workspace_shared_when_active",
            ),
        ),
    ]
