# Generated by plane-custom v1.33b (manual, non auto-generated)
#
# PATCH (plane-custom) v1.33b:
#  Crea tabella `active_timers` per il timer del Time Tracking.
#
#  Operazioni:
#    1. CreateModel ActiveTimer.
#    2. UNIQUE constraint su user_id (1 timer per user max, enforced
#       a livello DB).
#
#  Effetto su DB esistente:
#    - Tabella nuova, vuota. Nessun impatto su record esistenti.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0124_v133a_time_logs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveTimer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_active_timers",
                        to="db.issue",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_timer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_active_timers",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Timer",
                "verbose_name_plural": "Active Timers",
                "db_table": "active_timers",
                "ordering": ("-started_at",),
            },
        ),
    ]
