# Generated by plane-custom v1.33e (manual, non auto-generated)
#
# PATCH (plane-custom) v1.33e:
#  Crea tabella `workspace_feature_settings` per flag toggle per-workspace.
#  Tabella generica riusabile per Meetings v1.34 e future feature.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0125_v133b_active_timer"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceFeatureSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_settings",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Feature Settings",
                "verbose_name_plural": "Workspace Feature Settings",
                "db_table": "workspace_feature_settings",
            },
        ),
    ]
