# Generated by plane-custom v1.33a (manual, non auto-generated)
#
# PATCH (plane-custom) v1.33a:
#  Crea tabella `time_logs` per il sistema di tracking ore.
#
#  Operazioni:
#    1. CreateModel TimeLog con tutti i campi descritti in time_log.py.
#    2. CheckConstraint duration_seconds in (0, 86400*7].
#    3. 4 Index per i pattern di query principali (user+date,
#       issue, workspace+date, approval_pending).
#
#  Effetto su DB esistente:
#    - Tabella nuova, vuota. Nessun impatto su record esistenti.
#    - Foreign key a workspace/project/issue/user con on_delete CASCADE
#      (tranne approved_by che e' SET_NULL: l'approver puo' essere
#      rimosso dal workspace senza distruggere lo storico).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_v122a_project_is_hidden"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("duration_seconds", models.IntegerField()),
                ("logged_at", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual entry"), ("timer", "Timer stop")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("timer_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-approved (no workflow)"),
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_time_logs",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_time_logs",
                        to="db.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_time_logs",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "db_table": "time_logs",
                "ordering": ("-logged_at", "-created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="timelog",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_seconds__gt", 0))
                & models.Q(("duration_seconds__lte", 604800)),
                name="time_log_duration_seconds_range",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "-logged_at"],
                name="time_log_user_logged_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["issue", "-logged_at"],
                name="time_log_issue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["workspace", "logged_at"],
                name="time_log_ws_logged_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["workspace", "approval_status"],
                name="time_log_pending_idx",
                condition=models.Q(("approval_status", "pending")),
            ),
        ),
    ]
